[env:my_board]
platform  = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino

board     = my_board
board_dir = ${PROJECT_DIR}/boards

; Tells pioarduino-build.py where to find the variant folder.
; Maps to board_config["build.variants_dir"] in the build script:
;   https://github.com/espressif/arduino-esp32/blob/master/tools/pioarduino-build.py
board_build.variants_dir = variants
board_build.variant      = my_board

monitor_speed = 115200
upload_speed  = 921600
